# Site settings
title: "바보 프로틴의 개발 블로그"
description: "Python, 딥러닝, 머신러닝을 공부하고 프로젝트를 기록하는 블로그입니다."
baseurl: ""
url: "https://1di0t.github.io"
author:
  name: "1di0t"
  email: ""
  github: "1di0t"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
future: true

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
  auto_ids: true
  toc_levels: 1..6

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:name/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Jekyll Archives - 수동 카테고리 페이지 사용으로 비활성화
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tags/:name/'

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  - BLOG_REQUIREMENTS.md

# Include
include:
  - _pages
  - _posts/**
  - category/**

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  # - jekyll-archives  # 수동 카테고리 페이지 사용으로 비활성화

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      comments: true
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: "assets/images"
    values:
      image: true
