/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './_layouts/**/*.html',
    './_includes/**/*.html',
    './_posts/**/*.{md,html}',
    './_pages/**/*.{md,html}',
    './index.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        // 2025 트렌드: 따뜻한 뉴트럴 톤 추가
        warm: {
          50: '#FDFBF7',
          100: '#F9F3EE',
          200: '#F4E9DF',
          300: '#E8D5C4',
          400: '#D4A574',
          500: '#C19A6B',
          600: '#B8905F',
          700: '#9A7A52',
          800: '#7D6344',
          900: '#5C4A35',
        },
        mocha: {
          50: '#FAF8F5',
          100: '#F5F0EA',
          200: '#EBE0D5',
          300: '#D9C7B8',
          400: '#C7AE9C',
          500: '#B59680', // Mocha Mousse - 2025 Pantone
          600: '#9A7D68',
          700: '#7F6454',
          800: '#644B40',
          900: '#49362C',
        },
      },
      fontFamily: {
        'sans': ['MaruBuri', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        'mono': ['D2Coding', 'JetBrains Mono', 'Consolas', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'lg': 'var(--radius)',
        'md': 'calc(var(--radius) - 2px)',
        'sm': 'calc(var(--radius) - 4px)',
        'xl': '1rem',
        '2xl': '1.5rem',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '100': '25rem',
        '112': '28rem',
      },
      lineHeight: {
        'relaxed': '1.75',
        'loose': '2',
      },
      boxShadow: {
        'warm': '0 4px 12px rgba(193, 154, 107, 0.12)',
        'warm-lg': '0 8px 24px rgba(193, 154, 107, 0.15)',
        'glow': '0 0 20px rgba(229, 119, 74, 0.2)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
